### ISSUE TITLE
Update Screenshots in Wiki Article

### ISSUE THREAD

**Issue by narinearraul** [csync/csync-server#18]
- [x] https://github.ibm.com/csync/csync-server/wiki/Create-a-CSync-Instance-on-Bluemix

- [ ] https://github.ibm.com/csync/csync-server/wiki/Create-a-CSync-Instance-on-Amazon-Web-Services

**Comment by narinearraul** [comment]
I've updated the article for the Bluemix.

**Comment by boopt2** [comment]
Removed the amazon article due to it being inaccurate and not working.

**Comment by boopt2** [comment]
Done
