### ISSUE TITLE
What use cases can you give for using this?

### ISSUE THREAD

**Issue by PhilAndrew** [csync/csync-server#33]
Hi! You said what it does but when and why do I want to use it?

**Comment by emmatucker15** [comment]
Hi Phil, Contextual Sync offers a simple, efficient solution when building multi-channel applications. Our lab has built quite a few things using the technology. For example, a Stadium replica (https://www.ibm.com/innovation/milab/work/ibm-stadium-experience/) that used CSync to synchronize a mobile app, lights in our "stadium", video, and noises. We then implemented logic on top of CSync that triggered different events when a team scored or the game ended.  We also built the sample apps, which are simple chat apps that use CSync to easily enable offline access, up to date messaging, and access controls. We experimented with CSync in relation to a security service as well where CSync updated user profile information in realtime across different user groups. Would be great to hear how you end up using it if you'd like to join our slack channel at https://csync.slack.com/  :)
